<?php

/**
 * Base class that represents a row from the 'transactions_tracks' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 03/18/11 13:19:23
 *
 * @package    lib.model.om
 */
abstract class BaseTransactionsTracks extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        TransactionsTracksPeer
	 */
	protected static $peer;

	/**
	 * The value for the transactions_tracks_id field.
	 * @var        int
	 */
	protected $transactions_tracks_id;

	/**
	 * The value for the transactions_id field.
	 * @var        int
	 */
	protected $transactions_id;

	/**
	 * The value for the tracks_id field.
	 * @var        int
	 */
	protected $tracks_id;

	/**
	 * The value for the transactions_tracks_path field.
	 * @var        string
	 */
	protected $transactions_tracks_path;

	/**
	 * @var        Transactions
	 */
	protected $aTransactions;

	/**
	 * @var        Tracks
	 */
	protected $aTracks;

	/**
	 * @var        array TransactionsSaldo[] Collection to store aggregation of TransactionsSaldo objects.
	 */
	protected $collTransactionsSaldos;

	/**
	 * @var        Criteria The criteria used to select the current contents of collTransactionsSaldos.
	 */
	private $lastTransactionsSaldoCriteria = null;

	/**
	 * @var        array TransactionsTracksDownloads[] Collection to store aggregation of TransactionsTracksDownloads objects.
	 */
	protected $collTransactionsTracksDownloadss;

	/**
	 * @var        Criteria The criteria used to select the current contents of collTransactionsTracksDownloadss.
	 */
	private $lastTransactionsTracksDownloadsCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'TransactionsTracksPeer';

	/**
	 * Get the [transactions_tracks_id] column value.
	 * 
	 * @return     int
	 */
	public function getTransactionsTracksId()
	{
		return $this->transactions_tracks_id;
	}

	/**
	 * Get the [transactions_id] column value.
	 * 
	 * @return     int
	 */
	public function getTransactionsId()
	{
		return $this->transactions_id;
	}

	/**
	 * Get the [tracks_id] column value.
	 * 
	 * @return     int
	 */
	public function getTracksId()
	{
		return $this->tracks_id;
	}

	/**
	 * Get the [transactions_tracks_path] column value.
	 * 
	 * @return     string
	 */
	public function getTransactionsTracksPath()
	{
		return $this->transactions_tracks_path;
	}

	/**
	 * Set the value of [transactions_tracks_id] column.
	 * 
	 * @param      int $v new value
	 * @return     TransactionsTracks The current object (for fluent API support)
	 */
	public function setTransactionsTracksId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->transactions_tracks_id !== $v) {
			$this->transactions_tracks_id = $v;
			$this->modifiedColumns[] = TransactionsTracksPeer::TRANSACTIONS_TRACKS_ID;
		}

		return $this;
	} // setTransactionsTracksId()

	/**
	 * Set the value of [transactions_id] column.
	 * 
	 * @param      int $v new value
	 * @return     TransactionsTracks The current object (for fluent API support)
	 */
	public function setTransactionsId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->transactions_id !== $v) {
			$this->transactions_id = $v;
			$this->modifiedColumns[] = TransactionsTracksPeer::TRANSACTIONS_ID;
		}

		if ($this->aTransactions !== null && $this->aTransactions->getTransactionsId() !== $v) {
			$this->aTransactions = null;
		}

		return $this;
	} // setTransactionsId()

	/**
	 * Set the value of [tracks_id] column.
	 * 
	 * @param      int $v new value
	 * @return     TransactionsTracks The current object (for fluent API support)
	 */
	public function setTracksId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->tracks_id !== $v) {
			$this->tracks_id = $v;
			$this->modifiedColumns[] = TransactionsTracksPeer::TRACKS_ID;
		}

		if ($this->aTracks !== null && $this->aTracks->getTracksId() !== $v) {
			$this->aTracks = null;
		}

		return $this;
	} // setTracksId()

	/**
	 * Set the value of [transactions_tracks_path] column.
	 * 
	 * @param      string $v new value
	 * @return     TransactionsTracks The current object (for fluent API support)
	 */
	public function setTransactionsTracksPath($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->transactions_tracks_path !== $v) {
			$this->transactions_tracks_path = $v;
			$this->modifiedColumns[] = TransactionsTracksPeer::TRANSACTIONS_TRACKS_PATH;
		}

		return $this;
	} // setTransactionsTracksPath()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->transactions_tracks_id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->transactions_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->tracks_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->transactions_tracks_path = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 4; // 4 = TransactionsTracksPeer::NUM_COLUMNS - TransactionsTracksPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating TransactionsTracks object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aTransactions !== null && $this->transactions_id !== $this->aTransactions->getTransactionsId()) {
			$this->aTransactions = null;
		}
		if ($this->aTracks !== null && $this->tracks_id !== $this->aTracks->getTracksId()) {
			$this->aTracks = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TransactionsTracksPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = TransactionsTracksPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aTransactions = null;
			$this->aTracks = null;
			$this->collTransactionsSaldos = null;
			$this->lastTransactionsSaldoCriteria = null;

			$this->collTransactionsTracksDownloadss = null;
			$this->lastTransactionsTracksDownloadsCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TransactionsTracksPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseTransactionsTracks:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				TransactionsTracksPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseTransactionsTracks:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TransactionsTracksPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseTransactionsTracks:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseTransactionsTracks:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				TransactionsTracksPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aTransactions !== null) {
				if ($this->aTransactions->isModified() || $this->aTransactions->isNew()) {
					$affectedRows += $this->aTransactions->save($con);
				}
				$this->setTransactions($this->aTransactions);
			}

			if ($this->aTracks !== null) {
				if ($this->aTracks->isModified() || $this->aTracks->isNew()) {
					$affectedRows += $this->aTracks->save($con);
				}
				$this->setTracks($this->aTracks);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = TransactionsTracksPeer::TRANSACTIONS_TRACKS_ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = TransactionsTracksPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setTransactionsTracksId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += TransactionsTracksPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collTransactionsSaldos !== null) {
				foreach ($this->collTransactionsSaldos as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collTransactionsTracksDownloadss !== null) {
				foreach ($this->collTransactionsTracksDownloadss as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aTransactions !== null) {
				if (!$this->aTransactions->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aTransactions->getValidationFailures());
				}
			}

			if ($this->aTracks !== null) {
				if (!$this->aTracks->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aTracks->getValidationFailures());
				}
			}


			if (($retval = TransactionsTracksPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collTransactionsSaldos !== null) {
					foreach ($this->collTransactionsSaldos as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collTransactionsTracksDownloadss !== null) {
					foreach ($this->collTransactionsTracksDownloadss as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = TransactionsTracksPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getTransactionsTracksId();
				break;
			case 1:
				return $this->getTransactionsId();
				break;
			case 2:
				return $this->getTracksId();
				break;
			case 3:
				return $this->getTransactionsTracksPath();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = TransactionsTracksPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getTransactionsTracksId(),
			$keys[1] => $this->getTransactionsId(),
			$keys[2] => $this->getTracksId(),
			$keys[3] => $this->getTransactionsTracksPath(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = TransactionsTracksPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setTransactionsTracksId($value);
				break;
			case 1:
				$this->setTransactionsId($value);
				break;
			case 2:
				$this->setTracksId($value);
				break;
			case 3:
				$this->setTransactionsTracksPath($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = TransactionsTracksPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setTransactionsTracksId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setTransactionsId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setTracksId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setTransactionsTracksPath($arr[$keys[3]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(TransactionsTracksPeer::DATABASE_NAME);

		if ($this->isColumnModified(TransactionsTracksPeer::TRANSACTIONS_TRACKS_ID)) $criteria->add(TransactionsTracksPeer::TRANSACTIONS_TRACKS_ID, $this->transactions_tracks_id);
		if ($this->isColumnModified(TransactionsTracksPeer::TRANSACTIONS_ID)) $criteria->add(TransactionsTracksPeer::TRANSACTIONS_ID, $this->transactions_id);
		if ($this->isColumnModified(TransactionsTracksPeer::TRACKS_ID)) $criteria->add(TransactionsTracksPeer::TRACKS_ID, $this->tracks_id);
		if ($this->isColumnModified(TransactionsTracksPeer::TRANSACTIONS_TRACKS_PATH)) $criteria->add(TransactionsTracksPeer::TRANSACTIONS_TRACKS_PATH, $this->transactions_tracks_path);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(TransactionsTracksPeer::DATABASE_NAME);

		$criteria->add(TransactionsTracksPeer::TRANSACTIONS_TRACKS_ID, $this->transactions_tracks_id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getTransactionsTracksId();
	}

	/**
	 * Generic method to set the primary key (transactions_tracks_id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setTransactionsTracksId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of TransactionsTracks (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setTransactionsId($this->transactions_id);

		$copyObj->setTracksId($this->tracks_id);

		$copyObj->setTransactionsTracksPath($this->transactions_tracks_path);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getTransactionsSaldos() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addTransactionsSaldo($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getTransactionsTracksDownloadss() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addTransactionsTracksDownloads($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setTransactionsTracksId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     TransactionsTracks Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     TransactionsTracksPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new TransactionsTracksPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Transactions object.
	 *
	 * @param      Transactions $v
	 * @return     TransactionsTracks The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setTransactions(Transactions $v = null)
	{
		if ($v === null) {
			$this->setTransactionsId(NULL);
		} else {
			$this->setTransactionsId($v->getTransactionsId());
		}

		$this->aTransactions = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Transactions object, it will not be re-added.
		if ($v !== null) {
			$v->addTransactionsTracks($this);
		}

		return $this;
	}


	/**
	 * Get the associated Transactions object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Transactions The associated Transactions object.
	 * @throws     PropelException
	 */
	public function getTransactions(PropelPDO $con = null)
	{
		if ($this->aTransactions === null && ($this->transactions_id !== null)) {
			$this->aTransactions = TransactionsPeer::retrieveByPk($this->transactions_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aTransactions->addTransactionsTrackss($this);
			 */
		}
		return $this->aTransactions;
	}

	/**
	 * Declares an association between this object and a Tracks object.
	 *
	 * @param      Tracks $v
	 * @return     TransactionsTracks The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setTracks(Tracks $v = null)
	{
		if ($v === null) {
			$this->setTracksId(NULL);
		} else {
			$this->setTracksId($v->getTracksId());
		}

		$this->aTracks = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Tracks object, it will not be re-added.
		if ($v !== null) {
			$v->addTransactionsTracks($this);
		}

		return $this;
	}


	/**
	 * Get the associated Tracks object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Tracks The associated Tracks object.
	 * @throws     PropelException
	 */
	public function getTracks(PropelPDO $con = null)
	{
		if ($this->aTracks === null && ($this->tracks_id !== null)) {
			$this->aTracks = TracksPeer::retrieveByPk($this->tracks_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aTracks->addTransactionsTrackss($this);
			 */
		}
		return $this->aTracks;
	}

	/**
	 * Clears out the collTransactionsSaldos collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addTransactionsSaldos()
	 */
	public function clearTransactionsSaldos()
	{
		$this->collTransactionsSaldos = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collTransactionsSaldos collection (array).
	 *
	 * By default this just sets the collTransactionsSaldos collection to an empty array (like clearcollTransactionsSaldos());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initTransactionsSaldos()
	{
		$this->collTransactionsSaldos = array();
	}

	/**
	 * Gets an array of TransactionsSaldo objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this TransactionsTracks has previously been saved, it will retrieve
	 * related TransactionsSaldos from storage. If this TransactionsTracks is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array TransactionsSaldo[]
	 * @throws     PropelException
	 */
	public function getTransactionsSaldos($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TransactionsTracksPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTransactionsSaldos === null) {
			if ($this->isNew()) {
			   $this->collTransactionsSaldos = array();
			} else {

				$criteria->add(TransactionsSaldoPeer::TRANSACTIONS_TRACKS_ID, $this->transactions_tracks_id);

				TransactionsSaldoPeer::addSelectColumns($criteria);
				$this->collTransactionsSaldos = TransactionsSaldoPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(TransactionsSaldoPeer::TRANSACTIONS_TRACKS_ID, $this->transactions_tracks_id);

				TransactionsSaldoPeer::addSelectColumns($criteria);
				if (!isset($this->lastTransactionsSaldoCriteria) || !$this->lastTransactionsSaldoCriteria->equals($criteria)) {
					$this->collTransactionsSaldos = TransactionsSaldoPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastTransactionsSaldoCriteria = $criteria;
		return $this->collTransactionsSaldos;
	}

	/**
	 * Returns the number of related TransactionsSaldo objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related TransactionsSaldo objects.
	 * @throws     PropelException
	 */
	public function countTransactionsSaldos(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TransactionsTracksPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collTransactionsSaldos === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(TransactionsSaldoPeer::TRANSACTIONS_TRACKS_ID, $this->transactions_tracks_id);

				$count = TransactionsSaldoPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(TransactionsSaldoPeer::TRANSACTIONS_TRACKS_ID, $this->transactions_tracks_id);

				if (!isset($this->lastTransactionsSaldoCriteria) || !$this->lastTransactionsSaldoCriteria->equals($criteria)) {
					$count = TransactionsSaldoPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collTransactionsSaldos);
				}
			} else {
				$count = count($this->collTransactionsSaldos);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a TransactionsSaldo object to this object
	 * through the TransactionsSaldo foreign key attribute.
	 *
	 * @param      TransactionsSaldo $l TransactionsSaldo
	 * @return     void
	 * @throws     PropelException
	 */
	public function addTransactionsSaldo(TransactionsSaldo $l)
	{
		if ($this->collTransactionsSaldos === null) {
			$this->initTransactionsSaldos();
		}
		if (!in_array($l, $this->collTransactionsSaldos, true)) { // only add it if the **same** object is not already associated
			array_push($this->collTransactionsSaldos, $l);
			$l->setTransactionsTracks($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this TransactionsTracks is new, it will return
	 * an empty collection; or if this TransactionsTracks has previously
	 * been saved, it will retrieve related TransactionsSaldos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in TransactionsTracks.
	 */
	public function getTransactionsSaldosJoinProfiles($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TransactionsTracksPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTransactionsSaldos === null) {
			if ($this->isNew()) {
				$this->collTransactionsSaldos = array();
			} else {

				$criteria->add(TransactionsSaldoPeer::TRANSACTIONS_TRACKS_ID, $this->transactions_tracks_id);

				$this->collTransactionsSaldos = TransactionsSaldoPeer::doSelectJoinProfiles($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(TransactionsSaldoPeer::TRANSACTIONS_TRACKS_ID, $this->transactions_tracks_id);

			if (!isset($this->lastTransactionsSaldoCriteria) || !$this->lastTransactionsSaldoCriteria->equals($criteria)) {
				$this->collTransactionsSaldos = TransactionsSaldoPeer::doSelectJoinProfiles($criteria, $con, $join_behavior);
			}
		}
		$this->lastTransactionsSaldoCriteria = $criteria;

		return $this->collTransactionsSaldos;
	}

	/**
	 * Clears out the collTransactionsTracksDownloadss collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addTransactionsTracksDownloadss()
	 */
	public function clearTransactionsTracksDownloadss()
	{
		$this->collTransactionsTracksDownloadss = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collTransactionsTracksDownloadss collection (array).
	 *
	 * By default this just sets the collTransactionsTracksDownloadss collection to an empty array (like clearcollTransactionsTracksDownloadss());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initTransactionsTracksDownloadss()
	{
		$this->collTransactionsTracksDownloadss = array();
	}

	/**
	 * Gets an array of TransactionsTracksDownloads objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this TransactionsTracks has previously been saved, it will retrieve
	 * related TransactionsTracksDownloadss from storage. If this TransactionsTracks is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array TransactionsTracksDownloads[]
	 * @throws     PropelException
	 */
	public function getTransactionsTracksDownloadss($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TransactionsTracksPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTransactionsTracksDownloadss === null) {
			if ($this->isNew()) {
			   $this->collTransactionsTracksDownloadss = array();
			} else {

				$criteria->add(TransactionsTracksDownloadsPeer::TRANSACTIONS_TRACKS_ID, $this->transactions_tracks_id);

				TransactionsTracksDownloadsPeer::addSelectColumns($criteria);
				$this->collTransactionsTracksDownloadss = TransactionsTracksDownloadsPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(TransactionsTracksDownloadsPeer::TRANSACTIONS_TRACKS_ID, $this->transactions_tracks_id);

				TransactionsTracksDownloadsPeer::addSelectColumns($criteria);
				if (!isset($this->lastTransactionsTracksDownloadsCriteria) || !$this->lastTransactionsTracksDownloadsCriteria->equals($criteria)) {
					$this->collTransactionsTracksDownloadss = TransactionsTracksDownloadsPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastTransactionsTracksDownloadsCriteria = $criteria;
		return $this->collTransactionsTracksDownloadss;
	}

	/**
	 * Returns the number of related TransactionsTracksDownloads objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related TransactionsTracksDownloads objects.
	 * @throws     PropelException
	 */
	public function countTransactionsTracksDownloadss(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TransactionsTracksPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collTransactionsTracksDownloadss === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(TransactionsTracksDownloadsPeer::TRANSACTIONS_TRACKS_ID, $this->transactions_tracks_id);

				$count = TransactionsTracksDownloadsPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(TransactionsTracksDownloadsPeer::TRANSACTIONS_TRACKS_ID, $this->transactions_tracks_id);

				if (!isset($this->lastTransactionsTracksDownloadsCriteria) || !$this->lastTransactionsTracksDownloadsCriteria->equals($criteria)) {
					$count = TransactionsTracksDownloadsPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collTransactionsTracksDownloadss);
				}
			} else {
				$count = count($this->collTransactionsTracksDownloadss);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a TransactionsTracksDownloads object to this object
	 * through the TransactionsTracksDownloads foreign key attribute.
	 *
	 * @param      TransactionsTracksDownloads $l TransactionsTracksDownloads
	 * @return     void
	 * @throws     PropelException
	 */
	public function addTransactionsTracksDownloads(TransactionsTracksDownloads $l)
	{
		if ($this->collTransactionsTracksDownloadss === null) {
			$this->initTransactionsTracksDownloadss();
		}
		if (!in_array($l, $this->collTransactionsTracksDownloadss, true)) { // only add it if the **same** object is not already associated
			array_push($this->collTransactionsTracksDownloadss, $l);
			$l->setTransactionsTracks($this);
		}
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collTransactionsSaldos) {
				foreach ((array) $this->collTransactionsSaldos as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collTransactionsTracksDownloadss) {
				foreach ((array) $this->collTransactionsTracksDownloadss as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collTransactionsSaldos = null;
		$this->collTransactionsTracksDownloadss = null;
			$this->aTransactions = null;
			$this->aTracks = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseTransactionsTracks:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseTransactionsTracks::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseTransactionsTracks
