# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  # liczba gatunków do wygenerowania na podstonie z gatunkiem pod listą z trackami - See also
  genres_see_also_rand: 6
  # maksymalna długość nazwy tracka by się mieściła data dodania
  tracklist_max_name_length: 36
  # domyślna cena, w £
  default_prize: 1.40
  # domyślna cena, format tekstowy
  default_prize_string: £1.40
  # okres w dniach kiedy track jest nowy
  track_new_period: 5
  # lista tracków na stronie - do stronicowania
  max_tracks_on_list: 10
  # maksymalna długość opisu artysty na podstronie Artists
  max_profile_short_text_length: 80
  # liczba gatunków przy profilu
  profile_genres_amount: 2
  # contact form mail from
  contact_form_mail_from: no-reply@smashintracks.com
  # contact form mail to
  contact_form_mail_to: office@smashintracks.com
  # z ilu ostatnich dniach pokazuje bestsellery na głównej
  homepage_bestsellers_period: 7