# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  # liczba gatunków do wygenerowania na podstonie z gatunkiem pod listą z trackami - See also
  genres_see_also_rand: 6
  # liczba gatunków do wygenerowania na głównej pod listą New Tracks
  homepage_genres_new_tracks: 4
  # maksymalna długość nazwy tracka by się mieściła data dodania
  tracklist_max_name_length: 36
  # domyślna cena, w £. Zmień również define('TRACK_PRIZE', 140); i define('TRACK_PRIZE_HALF', 70); w web/paypal_status.php 1.40
  default_prize: 0.02
  # domyślna waluta
  default_prize_currency: £
  # domyślna cena, format tekstowy £1.40
  default_prize_string: £0.02
  # okres w dniach kiedy track jest nowy
  track_new_period: 10
  # lista tracków na stronie - do stronicowania
  max_tracks_on_list: 10
  # lista transakcji na stronie My Sales - do stronicowania
  max_transactions_on_list: 10
  # maksymalna długość opisu artysty na podstronie Artists
  max_profile_short_text_length: 80
  # liczba gatunków przy profilu
  profile_genres_amount: 2
  # contact form mail from
  contact_form_mail_from: no-reply@smashintracks.com
  # contact form mail to
  contact_form_mail_to: office@smashintracks.com
  # z ilu ostatnich dniach pokazuje bestsellery na głównej
  homepage_bestsellers_period: 7