# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

artists:
  url:     /artists
  param: { module: artists, action: show, section: artists }

artists_all:
  url:     /artists/all
  param: { module: artists, action: showAll, section: artists }

basket:
  url:     /basket
  param: { module: basket, action: show, section: basket }

basket_add:
  url:     /basket/add/:tracks_id
  class:   sfPropelRoute
  options: { model: Tracks, type: object }
  param: { module: basket, action: add, section: basket }
  requirements:
    sf_method: [get]

basket_remove:
  url:     /basket/remove/:tracks_id
  class:   sfPropelRoute
  options: { model: Tracks, type: object }
  param: { module: basket, action: remove, section: basket }
  requirements:
    sf_method: [get]

basket_paypal_checkout:
  url:     /basket/paypal-checkout/:transactions_id
  class:   sfPropelRoute
  options: { model: Transactions, type: object }
  param: { module: basket, action: payPalCheckout, section: basket }
  requirements:
    sf_method: [get]

charts:
  url:     /charts
  param: { module: charts, action: show, section: charts, subsection: this_week, period: 7 }

charts_3months:
  url:     /charts/last-3-months
  param: { module: charts, action: show, section: charts, subsection: last_3_months, period: 92 }

charts_all:
  url:     /charts/all-time
  param: { module: charts, action: show, section: charts, subsection: all_time, period: null }

contact:
  url:     /contact
  param: { module: contact, action: show, section: contact }

contact_thankyou:
  url:     /contact/thankyou
  param: { module: contact, action: thankyou, section: contact }

faq:
  url:     /faq
  param: { module: faq, action: show, section: faq }

genre:
  url:     /genre/:genres_path
  class:   sfPropelRoute
  options: { model: Genres, type: object }
  param:   { module: genre, action: show, section: home }
  requirements:
    sf_method: [get]

members:
  url:     /members
  param: { module: members, action: show, section: members }

members_my-downloads:
  url:     /members/my-downloads
  param: { module: members, action: myDownloads, section: my-downloads }

members_my-sales:
  url:     /members/my-sales
  param: { module: members, action: mySales, section: my-sales }

members_my-tracks:
  url:     /members/my-tracks
  param: { module: members, action: myTracks, section: my-tracks, subsection: all_tracks }

members_my-tracks_most_popular:
  url:     /members/my-tracks/most-popular
  param: { module: members, action: myTracks, section: my-tracks, subsection: most_popular }

members_my-tracks_in_wishlists:
  url:     /members/my-tracks/in-wishlists
  param: { module: members, action: myTracks, section: my-tracks, subsection: in_wishlists }

members_my-wishlist:
  url:     /members/my-wishlist
  param: { module: members, action: myWishlist, section: my-wishlist }

members_my-wishlist_add:
  url:     /members/my-wishlist/add/:tracks_id
  class:   sfPropelRoute
  options: { model: Tracks, type: object }
  param: { module: members, action: myWishlistAdd, section: my-wishlist }
  requirements:
    sf_method: [get]

members_my-wishlist_remove:
  url:     /members/my-wishlist/remove/:tracks_id
  class:   sfPropelRoute
  options: { model: Tracks, type: object }
  param: { module: members, action: myWishlistRemove, section: my-wishlist }
  requirements:
    sf_method: [get]

new-tracks:
  url:     /new-tracks
  param: { module: charts, action: newTracks, section: charts }

order_registered:
  url:     /order/:transactions_id
  class:   sfPropelRoute
  options: { model: Transactions, type: object }
  param: { module: order, action: show, section: order }
  requirements:
    sf_method: [get]

order_unregistered:
  url:     /order/:transactions_id/:transactions_path
  class:   sfPropelRoute
  options: { model: Transactions, type: object }
  param: { module: order, action: show, section: order }
  requirements:
    sf_method: [get]

order_download:
  url:     /order/download/:transactions_tracks_id/:tracks_path
  class:   sfPropelRoute
  options: { model: TransactionsTracks, type: object }
  param: { module: order, action: download, section: order }
  requirements:
    sf_method: [get]

profile:
  url:     /profile/:profiles_path
  class:   sfPropelRoute
  options: { model: Profiles, type: object }
  param:   { module: profile, action: show, section: artists }
  requirements:
    sf_method: [get]

register:
  url:     /register
  param: { module: register, action: show, section: register }

register_welcome:
  url:     /register/welcome
  param: { module: register, action: welcome, section: register }

sign-out:
  url:     /sign-out
  param: { module: metadata, action: signOut, section: home }

terms:
  url:     /terms-and-conditions
  param: { module: terms, action: show, section: terms }

track:
  url:     /track/:tracks_path
  class:   sfPropelRoute
  options: { model: Tracks, type: object }
  param:   { module: track, action: show, section: charts }
  requirements:
    sf_method: [get]

# default rules
homepage:
  url:   /
  param: { module: home, action: index, section: home, facebook: true }

# generic rules
# please, remove them by adding more specific rules
#default_index:
#  url:   /:module
#  param: { action: index }

#default:
#  url:   /:module/:action/*
