# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        SmashinTracks.com - Tracks you won't find anywhere else
    description:  SmashinTracks.com - Tracks you won't find anywhere else
    keywords:     SmashinTracks.com, SmashinTracks
    language:     en
    robots:       all

  stylesheets:    [style.css, smoothness/jquery-ui-1.10.1.custom.min.css]

  javascripts:    [jquery/jquery.js, jquery/jquery-ui-1.8.7.custom.min.js, jquery/jquery.select_drop_down.js, jquery/jquery.form.js, swfobject/swfobject.js, facebook_config.js, common.js, http://s7.addthis.com/js/250/addthis_widget.js#username=modul, addthis_config.js, google-analytics.js]

  has_layout:     true
  layout:         layout
