<?php


/**
 * Skeleton subclass for representing a row from the 'banners' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 02/03/11 19:41:20
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Banners extends BaseBanners {

        public function setBannersUrl($v)
	{
            if($v=='') $v = null;
            if ($v !== null) {
                    $v = (string) $v;
                    if((substr($v,0,7)!='http://') && (substr($v,0,8)!='https://') && (substr($v,0,6)!='ftp://')  && (substr($v,0,7)!='ftps://')) {
                        $v = 'http://'.$v;
                    }
            }
            return parent::setBannersUrl($v);                
	} // setBannersUrl()

        public function save(PropelPDO $con = null) {
            if($this->isNew()) {
                $max = BannersPeer::getMaxBannersOrder();
                $this->setBannersOrder($max+1);
            }
            return parent::save($con);
        }

} // Banners
