<?php


/**
 * Skeleton subclass for representing a row from the 'paypal_subscription_info' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 02/21/11 22:53:04
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class PaypalSubscriptionInfo extends BasePaypalSubscriptionInfo {

	/**
	 * Initializes internal state of PaypalSubscriptionInfo object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}

} // PaypalSubscriptionInfo
