<?php


/**
 * Skeleton subclass for performing query and update operations on the 'paypal_payment_info' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 02/21/11 22:53:03
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class PaypalPaymentInfoPeer extends BasePaypalPaymentInfoPeer {

} // PaypalPaymentInfoPeer
