<?php


/**
 * Skeleton subclass for performing query and update operations on the 'profiles' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 02/03/11 19:41:21
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ProfilesPeer extends BaseProfilesPeer {

    public static function getProfilesAscending($criteria = null) {
        if ($criteria === null) {
                $criteria = new Criteria(self::DATABASE_NAME);
        }
        elseif ($criteria instanceof Criteria)
        {
                $criteria = clone $criteria;
        }

        $criteria->add(self::PROFILES_DELETED, false);
        $criteria->addAscendingOrderByColumn(self::PROFILES_NAME);
        return self::doSelect($criteria);
    }

    public static function getActiveProfilesAscending($criteria = null) {
        if ($criteria === null) {
                $criteria = new Criteria(self::DATABASE_NAME);
        }
        elseif ($criteria instanceof Criteria)
        {
                $criteria = clone $criteria;
        }
        $criteria->add(self::PROFILES_BLOCKED, false);
        return self::getProfilesAscending($criteria);
    }
    
    public static function getActiveProfilesWithTracksAscending($criteria = null) {
        if ($criteria === null) {
                $criteria = new Criteria(self::DATABASE_NAME);
        }
        elseif ($criteria instanceof Criteria)
        {
                $criteria = clone $criteria;
        }
        $criteria = TracksPeer::addActiveTracksCriteria();
        $criteria->addJoin(self::PROFILES_ID, TracksPeer::PROFILES_ID);
        $criteria->addGroupByColumn(self::PROFILES_ID);
        return self::getActiveProfilesAscending($criteria);        
    }

    public static function getBlockedProfilesAscending($criteria = null) {
        if ($criteria === null) {
                $criteria = new Criteria(self::DATABASE_NAME);
        }
        elseif ($criteria instanceof Criteria)
        {
                $criteria = clone $criteria;
        }
        $criteria->add(self::PROFILES_BLOCKED, true);
        return self::getProfilesAscending($criteria);
    }

    public static function getProfilesOrderByDateCriteria($criteria = null) {
        if ($criteria === null) {
                $criteria = new Criteria(self::DATABASE_NAME);
        }
        elseif ($criteria instanceof Criteria)
        {
                $criteria = clone $criteria;
        }

        $criteria->add(self::PROFILES_DELETED, false);
        $criteria->addDescendingOrderByColumn(self::PROFILES_DATE);
        return $criteria;
    }

    public static function getActiveProfilesOrderByDateCriteria($criteria = null) {
        $criteria = self::getProfilesOrderByDateCriteria($criteria);
        $criteria->add(self::PROFILES_BLOCKED, false);
        return $criteria;
    }

    public static function getBlockedProfilesOrderByDateCriteria($criteria = null) {
        $criteria = self::getProfilesOrderByDateCriteria($criteria);
        $criteria->add(self::PROFILES_BLOCKED, true);
        return $criteria;
    }

    public static function getProfilesOrderByDate($criteria = null) {
        return self::doSelect(self::getProfilesOrderByDateCriteria($criteria));
    }

    public static function getMostPopularProfiles($criteria = null) {
        if ($criteria === null) {
                $criteria = new Criteria(self::DATABASE_NAME);
        }
        elseif ($criteria instanceof Criteria)
        {
                $criteria = clone $criteria;
        }
        $criteria->addJoin(self::PROFILES_ID, TracksPeer::PROFILES_ID);
        $criteria->addJoin(TracksPeer::TRACKS_ID, TransactionsTracksPeer::TRACKS_ID);
        $criteria->addGroupByColumn(self::PROFILES_ID);
        $criteria->addDescendingOrderByColumn('COUNT('.TracksPeer::TRACKS_ID.')'); // sortowanie po ilości tracków sprzedanych
        $criteria->setLimit(30);
        $profiles = self::doSelect($criteria);
        return $profiles;

    }



    public static function getProfileById($profiles_id, $criteria = null) {
        if ($criteria === null) {
                $criteria = new Criteria();
        }
        elseif ($criteria instanceof Criteria)
        {
                $criteria = clone $criteria;
        }
        $criteria->add(self::PROFILES_ID, $profiles_id);
        return self::doSelectOne($criteria);
    }

    public static function getActiveProfileById($profiles_id, $criteria = null) {
        if ($criteria === null) {
                $criteria = new Criteria();
        }
        elseif ($criteria instanceof Criteria) {
                $criteria = clone $criteria;
        }
        $criteria->add(self::PROFILES_BLOCKED, false);
        $criteria->add(self::PROFILES_DELETED, false);
        return self::getProfileById($profiles_id, $criteria);
    }

    public static function countActiveProfiles($criteria = null) {
        if ($criteria === null) {
                $criteria = new Criteria();
        }
        elseif ($criteria instanceof Criteria) {
                $criteria = clone $criteria;
        }
        $criteria->add(self::PROFILES_BLOCKED, false);
        $criteria->add(self::PROFILES_DELETED, false);
        return self::doCount($criteria);
    }
    
    public static function countActiveProfilesWithTracks() {
        $sql = 'SELECT COUNT(*) FROM `profiles` WHERE profiles.PROFILES_BLOCKED=false AND profiles.PROFILES_DELETED=false AND (select count(*) from tracks where tracks.tracks_accepted = 1 and tracks.tracks_deleted = 0 and tracks.profiles_id = profiles.profiles_id)>0';

        $connection = Propel::getConnection();
        $statement = $connection->prepare($sql);
        $statement->execute();
        $row = $statement->fetch();
        return $row[0];
    }
    
    public static function countActiveProfilesWithoutTracks() {
        $sql = 'SELECT COUNT(*) FROM `profiles` WHERE profiles.PROFILES_BLOCKED=false AND profiles.PROFILES_DELETED=false AND (select count(*) from tracks where tracks.tracks_accepted = 1 and tracks.tracks_deleted = 0 and tracks.profiles_id = profiles.profiles_id)=0';

        $connection = Propel::getConnection();
        $statement = $connection->prepare($sql);
        $statement->execute();
        $row = $statement->fetch();
        return $row[0];
    }

    public static function getProfileByEmail($profiles_email, $criteria = null) {
        if ($criteria === null) {
                $criteria = new Criteria();
        }
        elseif ($criteria instanceof Criteria)
        {
                $criteria = clone $criteria;
        }
        $criteria->add(self::PROFILES_EMAIL, $profiles_email, Criteria::LIKE);
        return self::doSelectOne($criteria);
    }

    public static function isProfileByEmail($profiles_email, $criteria = null) {
        if ($criteria === null) {
                $criteria = new Criteria();
        }
        elseif ($criteria instanceof Criteria)
        {
                $criteria = clone $criteria;
        }
        $criteria->add(self::PROFILES_EMAIL, $profiles_email, Criteria::LIKE);
        return self::doCount($criteria);
    }

    public static function getProfileByName($profiles_name, $criteria = null) {
        if ($criteria === null) {
                $criteria = new Criteria();
        }
        elseif ($criteria instanceof Criteria)
        {
                $criteria = clone $criteria;
        }
        $criteria->add(self::PROFILES_NAME, strtoupper($profiles_name), Criteria::LIKE);
        return self::doSelectOne($criteria);
    }

    public static function isProfileByName($profiles_name, $criteria = null) {
        if ($criteria === null) {
                $criteria = new Criteria();
        }
        elseif ($criteria instanceof Criteria)
        {
                $criteria = clone $criteria;
        }
        $criteria->add(self::PROFILES_NAME, strtoupper($profiles_name), Criteria::LIKE);
        return self::doCount($criteria);
    }

    public static function isProfileById($profiles_id, $criteria = null) {
        if ($criteria === null) {
                $criteria = new Criteria();
        }
        elseif ($criteria instanceof Criteria)
        {
                $criteria = clone $criteria;
        }
        $criteria->add(self::PROFILES_ID, $profiles_id);
        return self::doCount($criteria);
    }

    public static function isLoginCorrect($email, $pass) {
        $criteria = new Criteria();
        $criteria->add(self::PROFILES_EMAIL, $email, Criteria::LIKE);
        $criteria->add(self::PROFILES_PASSWORD, Smashin::generateHash($pass));
        if(empty($email) || empty($pass)) return 0;
        return self::doCount($criteria);
    }

    public static function isPassCorrect($id, $pass) {
        $criteria = new Criteria();
        $criteria->add(self::PROFILES_ID, $id);
        $criteria->add(self::PROFILES_PASSWORD, Smashin::generateHash($pass));
        if(empty($id) || empty($pass)) return 0;
        return self::doCount($criteria);
    }

    public static function isCookiePassCorrect($cookie_pass) {
        $cookie_pass_array = unserialize(base64_decode($cookie_pass));
        $id = (int)$cookie_pass_array[0];
        $pass = $cookie_pass_array[1];
        $criteria = new Criteria();
        $criteria->add(self::PROFILES_ID, $id);
        $profile = ProfilesPeer::doSelectOne($criteria);
        if(!is_object($profile)) return 0;
        $current_pass = $profile->getProfilesPassword();
        $generate_pass = Smashin::generateRememberMePass($current_pass);
        return ($pass==$generate_pass);
    }

    public static function getProfileByCookiePass($cookie_pass, $check_profile = true) {
        if($check_profile && !$this->isCookiePassCorrect($cookie_pass)) return null;
        $cookie_pass_array = unserialize(base64_decode($cookie_pass));
        $id = (int)$cookie_pass_array[0];
        $criteria = new Criteria();
        $criteria->add(self::PROFILES_ID, $id);
        return ProfilesPeer::doSelectOne($criteria);
    }

    public static function getProfileIfLoginCorrect($email, $pass) {
        $criteria = new Criteria();
        $criteria->add(self::PROFILES_EMAIL, $email);
        $criteria->add(self::PROFILES_PASSWORD, Smashin::generateHash($pass));
        if(empty($email) || empty($pass)) return null;
        return self::doSelectOne($criteria);
    }

    public static function isActiveProfileById($profiles_id, $criteria = null) {
        if ($criteria === null) {
                $criteria = new Criteria();
        }
        elseif ($criteria instanceof Criteria)
        {
                $criteria = clone $criteria;
        }
        $criteria->add(self::PROFILES_BLOCKED, false);
        $criteria->add(self::PROFILES_DELETED, false);
        return ProfilesPeer::isProfileById($profiles_id, $criteria);
    }

    public static function isActiveProfileByEmail($profiles_email, $criteria = null) {
        if ($criteria === null) {
                $criteria = new Criteria();
        }
        elseif ($criteria instanceof Criteria)
        {
                $criteria = clone $criteria;
        }
        $criteria->add(self::PROFILES_BLOCKED, false);
        $criteria->add(self::PROFILES_DELETED, false);
        return ProfilesPeer::isProfileByEmail($profiles_email, $criteria);
    }

    public static function isCurrentProfile() {
      $oUser = sfContext::getInstance()->getUser();
      if($oUser->hasAttribute('profile_id')) {
          $profile_id = $oUser->getAttribute('profile_id');
          return ProfilesPeer::isActiveProfileById($profile_id);
      }
    }

    public static function getCurrentProfile() {
        $oUser = sfContext::getInstance()->getUser();
        if($oUser->hasAttribute('profile_id')) {
          $profile_id = $oUser->getAttribute('profile_id');
          return self::getActiveProfileById($profile_id);
        } else {
            return null;
        }
    }

    public static function isAdminProfile() {
        $oUser = sfContext::getInstance()->getUser();
        if($oUser->hasAttribute('profile_id')) {
          $profile_id = $oUser->getAttribute('profile_id');
          return ($profile_id == sfConfig::get('app_admin_profile_id'));
        } else {
          return false;
        }
    }

    public static function getAdminProfile() {
        $profiles_id = sfConfig::get('app_admin_profile_id');
        return self::getProfileById($profiles_id);
    }

    public static function getAdminProfileId() {
        return sfConfig::get('app_admin_profile_id');
    }

    public static function getCurrentProfileId() {
        $oUser = sfContext::getInstance()->getUser();
        if($oUser->hasAttribute('profile_id')) {
          $profile_id = $oUser->getAttribute('profile_id');
          return $profile_id;
        } else {
            return null;
        }
    }


} // ProfilesPeer
