<?php


/**
 * Skeleton subclass for performing query and update operations on the 'profiles_baskets' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 02/03/11 19:41:21
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ProfilesBasketsPeer extends BaseProfilesBasketsPeer {
    public static function getProfilesBasketsById($basket_id, $criteria = null) {
        if ($criteria === null) {
                $criteria = new Criteria();
        }
        elseif ($criteria instanceof Criteria)
        {
                $criteria = clone $criteria;
        }
        $criteria->add(ProfilesBasketsPeer::PROFILES_BASKETS_ID, $basket_id);
        return ProfilesBasketsPeer::doSelectOne($criteria);
    }

    public static function getProfilesBasketsByProfileIdTrackId($profile_id, $track_id, $criteria = null) {
        if ($criteria === null) {
                $criteria = new Criteria();
        }
        elseif ($criteria instanceof Criteria)
        {
                $criteria = clone $criteria;
        }
        $criteria->add(ProfilesBasketsPeer::PROFILES_ID, $profile_id);
        $criteria->add(ProfilesBasketsPeer::TRACKS_ID, $track_id);
        return ProfilesBasketsPeer::doSelectOne($criteria);
    }
} // ProfilesBasketsPeer
