<?php


/**
 * Skeleton subclass for performing query and update operations on the 'tracks_votes' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 12/20/11 00:27:35
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class TracksVotesPeer extends BaseTracksVotesPeer {

} // TracksVotesPeer
