<?php


/**
 * Skeleton subclass for representing a row from the 'tracks' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 02/03/11 19:41:23
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Tracks extends BaseTracks {

	/**
	 * Initializes internal state of Tracks object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}

	public function getTracksTimeFormatted()
	{
		//return $this->getTracksTime();//5:41
                return number_format($this->getTracksTime()/100, 2, ':', '');
	}
        
	public function getTracksArtistUppercase()
	{
		return strtoupper($this->getTracksArtist());
	}

        public function getTracksTitleShorted() {
            $title = parent::getTracksTitle();
            if(strlen($title)>sfConfig::get('app_tracklist_max_name_length')) {
                $title = substr($title, 0, sfConfig::get('app_tracklist_max_name_length')).'..';
            }
            return $title;
        }

} // Tracks
