<?php


/**
 * Skeleton subclass for representing a row from the 'transactions_tracks' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 02/03/11 19:41:25
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class TransactionsTracks extends BaseTransactionsTracks {
    public function getTransactionsTracksValue() {
        $criteria = new Criteria();
        $criteria->add(TransactionsSaldoPeer::TRANSACTIONS_TRACKS_ID, $this->getTransactionsTracksId());
        $criteria->add(TransactionsSaldoPeer::TRANSACTIONS_SALDO_VALUE, 0, Criteria::GREATER_THAN);
        $criteria->addSelectColumn('SUM('.TransactionsSaldoPeer::TRANSACTIONS_SALDO_VALUE.')');
        $smtm = TransactionsSaldoPeer::doSelectStmt($criteria);
        $row = $smtm->fetch(PDO::FETCH_NUM);
        $saldo = $row[0];
        return Smashin::generate_prize($saldo/100);
    }
} // TransactionsTracks
