<?php


/**
 * Skeleton subclass for performing query and update operations on the 'transactions' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 02/03/11 19:41:24
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class TransactionsPeer extends BaseTransactionsPeer {
    public static function getTransactionById($transaction_id, $criteria = null) {
        if ($criteria === null) {
                $criteria = new Criteria();
        }
        elseif ($criteria instanceof Criteria)
        {
                $criteria = clone $criteria;
        }
        $criteria->add(TransactionsPeer::TRANSACTIONS_ID, $transaction_id);
        return self::doSelectOne($criteria);
    }

    public static function getLastDoneTransactions($amount = null, $criteria = null) {
        if ($criteria === null) {
                $criteria = new Criteria();
        }
        elseif ($criteria instanceof Criteria)
        {
                $criteria = clone $criteria;
        }
        if($amount!=null) $criteria->setLimit($amount); // limit dla transakcji a nie dla tracków, zakładam więc najbardziej pesymistyczny przypadek - 1 transkakcja = 1  track
        $criteria->add(TransactionsPeer::TRANSACTIONS_DONE, true);
        $criteria->addDescendingOrderByColumn(TransactionsPeer::TRANSACTIONS_DATE);
        return self::doSelect($criteria);
    }
} // TransactionsPeer
